apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary-worker
  namespace: aniket-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundary-worker
  template:
    metadata:
      labels:
        app: boundary-worker
    spec:
      containers:
      - name: boundary-worker
        image: hashicorp/boundary:0.21.0
        command:
          - boundary
        args:
          - server
          - -config=/boundary/boundary-worker.hcl
        volumeMounts:
        - name: config
          mountPath: /boundary/boundary-worker.hcl
          subPath: boundary-worker.hcl
        - name: auth
          mountPath: /boundary/auth
      volumes:
      - name: config
        configMap:
          name: boundary-worker-config
      - name: auth
        emptyDir: {}
