apiVersion: batch/v1
kind: Job
metadata:
  name: boundary-db-init
  namespace: aniket-test
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: boundary-init
        image: hashicorp/boundary:0.15
        command:
          - boundary
          - database
          - init
          - -config=/boundary/boundary.hcl
        volumeMounts:
        - name: config
          mountPath: /boundary
      volumes:
      - name: config
        configMap:
          name: boundary-config
