apiVersion: v1
kind: Service
metadata:
  name: boundary
  namespace: aniket-test
spec:
  selector:
    app: boundary-controller
  ports:
  - name: api
    port: 9200
    targetPort: 9200
  - name: cluster
    port: 9201
    targetPort: 9201
