apiVersion: v1
kind: Service
metadata:
  name: boundary-cluster
  namespace: aniket-test
spec:
  type: NodePort
  selector:
    app: boundary-controller
  ports:
  - name: cluster
    port: 9201
    targetPort: 9201
    nodePort: 32001
