apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary-postgres
  namespace: aniket-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundary-postgres
  template:
    metadata:
      labels:
        app: boundary-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: boundary
        - name: POSTGRES_USER
          value: boundary
        - name: POSTGRES_PASSWORD
          value: boundarypass
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: boundary-postgres-data
